### ISSUE TITLE
Slow loading times 

### ISSUE THREAD

**Issue by Jflick58** [yunyu/SpeechDrop#3]
We’re expercing some slow loading times which are causing timeouts at a debate camp. I am willing to help fund the hosting costs if we can upgrade bandwidth.

**Comment by yunyu** [comment]
The site is currently hosted on a DigitalOcean instance with shared gigabit connection - I haven't been experiencing particularly long loading times, so I assume that this is probably an issue with CloudFlare (the CDN service). Are you still experiencing this?

**Comment by Jflick58** [comment]
I haven't since then. Those who had issues were all on a university wifi network while I was connecting on my iPad with it's LTE connection, so do you think its possible that cloudflare would meter multiple connections from the same external IP? That could explain why only those who were connected to the university network were having issues. I had a student confirm the network was working properly with other sites, and I didn't see anything abnormal when I had a student run a speed test, so I don't think it was a problem with the local wi-fi.

**Comment by Jflick58** [comment]
I'll talk to folks at the first tournament of our season to figure out if they are consistently having issues or if this was just a fluke.

**Comment by Jflick58** [comment]
No issues this past weekend. I will close the issue.
