### ISSUE TITLE
404 when downloading documents

### ISSUE THREAD

**Issue by Jflick58** [yunyu/SpeechDrop#5]
We're experiencing a consistent 404 error on any files we try to download. I've tried this on different OSes, browsers, and networks and I still get the same Nginix 404 Page. 

Error can be encountered at the following: https://media.speechdrop.net/uploads/CNPwwe/2/network.gv.pdf

I tried creating a different room and still experienced the same issue.

**Comment by yunyu** [comment]
It was a permission issue, thanks for letting me know.
